
-- --------------------------------------------------------

--
-- Structure de la table `cc_lieu_menu`
--

DROP TABLE IF EXISTS `cc_lieu_menu`;
CREATE TABLE `cc_lieu_menu` (
  `id` int(12) UNSIGNED NOT NULL,
  `lieutech` varchar(150) NOT NULL,
  `caption` varchar(30) NOT NULL,
  `url` varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `cc_lieu_menu`
--

INSERT INTO `cc_lieu_menu` (`id`, `lieutech`, `caption`, `url`) VALUES
(1, 'a.mairie', '', 'Boutique'),
(6, 'Est.comm.imp', 'Cabine téléphonique', 'TelephonerCabine'),
(15, 'A.pizza', 'El ristorante', 'Boutique'),
(18, 'A.pizza', 'Table de soin', 'Soigner'),
(19, 'A', 'Soigner façon crevard', 'Soigner'),
(20, 'A.douanes', 'Soigner', 'Soigner'),
(21, 'A.hopital', 'Soigner', 'Soigner'),
(22, 'A.parc', 'Etudier', 'Etudier'),
(24, 'A.rien', 'Ordinateur fixe', 'OrdinateurFixe'),
(25, 'A.rien', 'Cabine telephonique', 'TelephonerCabine'),
(26, 'A.hopital.operation', 'Opérer', 'Soigner'),
(27, 'A.parc', 'Réparer ses protections', 'ReparerDefense'),
(28, 'A.parc', 'Réparer son arme', 'ReparerArme'),
(29, 'A.pizza.cuisine', 'Casier de rangement', 'CasiersListe'),
(30, 'A.rien', 'Mairie', 'Mairie'),
(31, 'A.rien', 'Banque', 'Banque'),
(32, 'A.rien', 'Bibliotheque', 'Biblio'),
(33, 'A.rien', 'Rangements', 'CasiersListe'),
(34, 'A.rien', 'Guichet', 'Guichet'),
(35, 'A.modules', '', 'Etudier'),
(36, 'A.hopital.operation', 'Labo', 'LaboDrogue'),
(37, 'A.rien', 'Laboratoire Drogue', 'LaboDrogue'),
(38, 'A.pizza', 'Livre de cuisine', 'Etudier'),
(39, 'A.pizza', 'Boite à pizza vide', 'CasiersListe'),
(40, 'A.modules', 'Distributeur', 'Guichet'),
(41, 'A.modules', 'Banque', 'Banque'),
(42, 'A.modules', 'Ordinateur', 'OrdinateurFixe'),
(43, 'A.modules', '', 'Biblio'),
(44, 'A.modules', 'Soin', 'Soigner'),
(45, 'A.modules', 'Labo de drogue', 'LaboDrogue'),
(46, 'CV.hopital', 'Pharmacie', 'Boutique'),
(47, 'CV.hopital.Hall', 'Soins', 'Soigner'),
(49, 'CV.hopital.e1.bloc', 'Opération', 'Soigner'),
(50, 'CV.hopital.e1.si', 'Aténuer les souffrances', 'Soigner'),
(51, 'Sud.clerks', 'Passer à la caisse', 'Boutique'),
(53, 'Ouest.auberge', 'Règlement', 'Biblio'),
(54, 'Ouest.auberge.cave', 'Soigner', 'Soigner'),
(55, 'Ouest.auberge.biblio', 'Lire des bouquins', 'Etudier'),
(56, 'Ouest.hopital.consu', 'Soigner', 'Soigner'),
(73, 'Ouest.gloo', 'Commander à boire', 'Boutique'),
(74, 'Ouest.gloo.fum', 'Commander à fumer', 'Boutique'),
(76, 'Est.dojo', 'S\'entrainer', 'Etudier'),
(77, 'Nord.redv', 'Comptoir', 'Boutique'),
(80, 'Nord.casino', 'Machine à sous', 'Casino'),
(81, 'Nord.redv.priv', 'Labo', 'LaboDrogue'),
(82, 'Nord.sex', 'Boutique', 'Boutique'),
(83, 'CV.centralp.serre', 'Travailler', 'Producteur'),
(84, 'CV.centralp.ile', 'Travailler', 'Producteur'),
(88, 'CV.mairie', 'Parler à la secrétaire', 'Mairie'),
(92, 'CV.police', 'Machine à café', 'Boutique'),
(93, 'Est.comm.flam', 'Acheter', 'Boutique'),
(94, 'Est.Electro', 'Passer à la caisse', 'Boutique'),
(96, 'Transit.passage', 'VISA VERT MJ GLANDEUR', 'Mairie'),
(97, 'Ouest.biblio', '', 'Biblio'),
(99, 'CV.police.asc.Sts', 'Ordinateur 1', 'OrdinateurFixe'),
(100, 'CV.police.asc.Sts', 'Ordinateur 2', 'OrdinateurFixe'),
(101, 'CV.police.asc.direction', 'Ordinateur', 'OrdinateurFixe'),
(102, 'CV.police.asc.bureaux', 'Ordinateur', 'OrdinateurFixe'),
(104, 'Ouest.cat', 'Commander à manger', 'Boutique'),
(105, 'Est.sushi', 'Restaurant', 'Boutique'),
(106, 'Sud.boxe', 'Acheter équipement', 'Boutique'),
(107, 'Sud.CDC', '', 'Distributeur'),
(108, 'Sud.recup', 'Travailler', 'Producteur'),
(109, 'Est.bank', 'Guichets', 'Banque'),
(110, 'CV.towerTV', 'DomTel', 'Banque'),
(112, 'Sud.Snack', 'Comptoir', 'Boutique'),
(114, 'Ouest.univ.Bibli', 'Bibliothèque', 'Biblio'),
(116, 'CV.towerTV.bur', 'Ordinateur', 'OrdinateurFixe'),
(117, 'CV.towerTV.work', 'Ordinateurs', 'OrdinateurFixe'),
(118, 'Est.comm.Gap', 'Shopping', 'Boutique'),
(120, 'Nord.casino', 'Commander des rafraîchissement', 'Boutique'),
(121, 'CV.agence', 'Documents', 'Biblio'),
(122, 'Est.comm.imp', 'Boutique', 'Boutique'),
(123, 'Ouest.univ.bur1', 'Mini-frigo', 'CasiersListe'),
(126, 'Sud.boxe.bur', 'Coffre à code', 'CasiersListe'),
(127, 'Sud.boxe.vest', 'Casiers', 'CasiersListe'),
(128, 'Sud.recup.for', 'Vitrine', 'Boutique'),
(130, 'Ouest.crema', 'Faire un achat', 'Boutique'),
(131, 'Sud.recup.ate', 'Armoire', 'CasiersListe'),
(132, 'Est.Electro.Atelier', 'La réserve', 'CasiersListe'),
(134, 'Nord.ruelle.Scrap.stock', 'Casier', 'CasiersListe'),
(135, 'Nord.ruelle.Scrap', 'Comptoir', 'Boutique'),
(136, 'Ouest.univ.prov', 'Ordinateur', 'OrdinateurFixe'),
(137, 'Nord.auberge.c2med', 'Armoire', 'CasiersListe'),
(138, 'Nord.auberge.c2med', 'media', 'MediaListe'),
(139, 'CV.towerTV.régie', 'Utiliser la régie', 'MediaListe'),
(143, 'CV.police', 'Regarder la TV', 'MediaListe'),
(144, 'CV.police.asc.bureaux', 'Regarder la TV', 'MediaListe'),
(145, 'CV.t1.etage1.Room1', 'Regarder la TV', 'MediaListe'),
(146, 'Est.comm', 'Regarder la TV', 'MediaListe'),
(147, 'Est.pavillons.hall.eta1.c1', 'Regarder la TV', 'MediaListe'),
(148, 'Est.sushi', 'Regarder la TV', 'MediaListe'),
(150, 'Nord.redv', 'Regarder la TV', 'MediaListe'),
(151, 'Ouest.cat', 'Regarder la TV', 'MediaListe'),
(153, 'Sud.Snack', 'Regarder la TV', 'MediaListe'),
(154, 'CV.t1.etage1.room2', 'Regarder la TV', 'MediaListe'),
(155, 'CV.t1.etage10.room19', 'Regarder la TV', 'MediaListe'),
(156, 'CV.t1.etage10.room20', 'Regarder la TV', 'MediaListe'),
(157, 'CV.t1.etage11.room21', 'Regarder la TV', 'MediaListe'),
(158, 'CV.t1.etage11.room22', 'Regarder la TV', 'MediaListe'),
(159, 'CV.t1.etage12.room23', 'Regarder la TV', 'MediaListe'),
(160, 'CV.t1.etage12.room24', 'Regarder la TV', 'MediaListe'),
(161, 'CV.t1.etage13.room25', 'Regarder la TV', 'MediaListe'),
(162, 'CV.t1.etage13.room26', 'Regarder la TV', 'MediaListe'),
(163, 'CV.t1.etage14.room27', 'Regarder la TV', 'MediaListe'),
(164, 'CV.t1.etage14.room28', 'Regarder la TV', 'MediaListe'),
(165, 'CV.t1.etage15.room29', 'Regarder la TV', 'MediaListe'),
(166, 'CV.t1.etage15.Room30', 'Regarder la TV', 'MediaListe'),
(167, 'CV.t1.etage16.room31', 'Regarder la TV', 'MediaListe'),
(168, 'CV.t1.etage16.Room32', 'Regarder la TV', 'MediaListe'),
(169, 'CV.t1.etage17.room33', 'Regarder la TV', 'MediaListe'),
(170, 'CV.t1.etage17.room34', 'Regarder la TV', 'MediaListe'),
(171, 'CV.t1.etage18.room35', 'Regarder la TV', 'MediaListe'),
(172, 'CV.t1.etage18.room36', 'Regarder la TV', 'MediaListe'),
(173, 'CV.t1.etage19.room37', 'Regarder la TV', 'MediaListe'),
(175, 'CV.t1.etage19.room38', 'Regarder la TV', 'MediaListe'),
(176, 'CV.t1.etage2.room3', 'Regarder la TV', 'MediaListe'),
(177, 'CV.t1.etage2.Room4', 'Regarder la TV', 'MediaListe'),
(178, 'CV.t1.etage20.Room39', 'Regarder la TV', 'MediaListe'),
(179, 'CV.t1.etage20.Room40', 'Regarder la TV', 'MediaListe'),
(180, 'CV.t1.etage21.Room41', 'Regarder la TV', 'MediaListe'),
(181, 'CV.t1.etage21.Room42', 'Regarder la TV', 'MediaListe'),
(182, 'CV.t1.etage3.room5', 'Regarder la TV', 'MediaListe'),
(184, 'CV.t1.etage3.Room6', 'Regarder la TV', 'MediaListe'),
(185, 'CV.t1.etage4.room7', 'Regarder la TV', 'MediaListe'),
(186, 'CV.t1.etage4.Room8', 'Regarder la TV', 'MediaListe'),
(187, 'CV.t1.etage5.room10', 'Regarder la TV', 'MediaListe'),
(188, 'CV.t1.etage5.room9', 'Regarder la TV', 'MediaListe'),
(189, 'CV.t1.etage6.room11', 'Regarder la TV', 'MediaListe'),
(190, 'CV.t1.etage6.room12', 'Regarder la TV', 'MediaListe'),
(191, 'CV.t1.etage7.room13', 'Regarder la TV', 'MediaListe'),
(192, 'CV.t1.etage7.room14', 'Regarder la TV', 'MediaListe'),
(193, 'CV.t1.etage8.Room15', 'Regarder la TV', 'MediaListe'),
(194, 'CV.t1.etage8.room16', 'Regarder la TV', 'MediaListe'),
(195, 'CV.t1.etage9.room17', 'Regarder la TV', 'MediaListe'),
(196, 'CV.t1.etage9.room18', 'Regarder la TV', 'MediaListe'),
(197, 'Est.pavillons.hall.eta1.c2', 'Regarder la TV', 'MediaListe'),
(198, 'Est.pavillons.hall.eta1.c3', 'Regarder la TV', 'MediaListe'),
(199, 'Est.pavillons.hall.eta1.c4', 'Regarder la TV', 'MediaListe'),
(201, 'Est.pavillons.hall.eta1.c5', 'Regarder la TV', 'MediaListe'),
(202, 'Est.pavillons.hall.eta2.c1', 'Regarder la TV', 'MediaListe'),
(203, 'Est.pavillons.hall.eta2.c2', 'Regarder la TV', 'MediaListe'),
(204, 'Est.pavillons.hall.eta2.c3', 'Regarder la TV', 'MediaListe'),
(205, 'Est.pavillons.hall.eta2.c4', 'Regarder la TV', 'MediaListe'),
(206, 'Est.pavillons.hall.eta2.c5', 'Regarder la TV', 'MediaListe'),
(207, 'Est.pavillons.hall.eta3.c1', 'Regarder la TV', 'MediaListe'),
(208, 'Est.pavillons.hall.eta3.c2', 'Regarder la TV', 'MediaListe'),
(209, 'Est.pavillons.hall.eta3.c3', 'Regarder la TV', 'MediaListe'),
(210, 'Est.pavillons.hall.eta3.c4', 'Regarder la TV', 'MediaListe'),
(211, 'Est.pavillons.hall.eta3.c5', 'Regarder la TV', 'MediaListe'),
(212, 'CV.t2.Etage1.room1', 'Regarder la TV', 'MediaListe'),
(214, 'CV.t2.Etage1.Room3', 'Regarder la TV', 'MediaListe'),
(215, 'CV.t2.etage10.Room28', 'Regarder la TV', 'MediaListe'),
(216, 'CV.t2.etage10.Room29', 'Regarder la TV', 'MediaListe'),
(217, 'CV.t2.etage10.Room30', 'Regarder la TV', 'MediaListe'),
(218, 'CV.t2.Etage11.Room31', 'Regarder la TV', 'MediaListe'),
(219, 'CV.t2.Etage11.Room32', 'Regarder la TV', 'MediaListe'),
(220, 'CV.t2.Etage11.Room33', 'Regarder la TV', 'MediaListe'),
(221, 'CV.t2.etage12.Room34', 'Regarder la TV', 'MediaListe'),
(222, 'CV.t2.etage12.Room35', 'Regarder la TV', 'MediaListe'),
(223, 'CV.t2.etage12.Room36', 'Regarder la TV', 'MediaListe'),
(224, 'CV.t2.etage13.Room37', 'Regarder la TV', 'MediaListe'),
(225, 'CV.t2.etage13.Room38', 'Regarder la TV', 'MediaListe'),
(226, 'CV.t2.etage13.Room39', 'Regarder la TV', 'MediaListe'),
(227, 'CV.t2.etage14.Room40', 'Regarder la TV', 'MediaListe'),
(228, 'CV.t2.etage14.Room41', 'Regarder la TV', 'MediaListe'),
(229, 'CV.t2.etage14.Room42', 'Regarder la TV', 'MediaListe'),
(230, 'CV.t2.etage15.Room43', 'Regarder la TV', 'MediaListe'),
(231, 'CV.t2.etage15.Room44', 'Regarder la TV', 'MediaListe'),
(232, 'CV.t2.etage15.Room45', 'Regarder la TV', 'MediaListe'),
(233, 'CV.t2.etage16.Room46', 'Regarder la TV', 'MediaListe'),
(234, 'CV.t2.etage16.Room47', 'Regarder la TV', 'MediaListe'),
(235, 'CV.t2.etage16.Room48', 'Regarder la TV', 'MediaListe'),
(236, 'CV.t2.etage17.Room49', 'Regarder la TV', 'MediaListe'),
(237, 'CV.t2.etage17.Room50', 'Regarder la TV', 'MediaListe'),
(238, 'CV.t2.etage17.room51', 'Regarder la TV', 'MediaListe'),
(239, 'CV.t2.Etage18.Room52', 'Regarder la TV', 'MediaListe'),
(240, 'CV.t2.Etage18.Room53', 'Regarder la TV', 'MediaListe'),
(241, 'CV.t2.Etage18.Room54', 'Regarder la TV', 'MediaListe'),
(243, 'CV.t2.etage19.Room55', 'Regarder la TV', 'MediaListe'),
(244, 'CV.t2.etage19.Room56', 'Regarder la TV', 'MediaListe'),
(245, 'CV.t2.etage19.room57', 'Regarder la TV', 'MediaListe'),
(246, 'CV.t2.etage2.Room4', 'Regarder la TV', 'MediaListe'),
(247, 'CV.t2.etage2.Room5', 'Regarder la TV', 'MediaListe'),
(248, 'CV.t2.etage2.Room6', 'Regarder la TV', 'MediaListe'),
(249, 'CV.t2.Etage20.room58', 'Regarder la TV', 'MediaListe'),
(250, 'CV.t2.Etage20.Room59', 'Regarder la TV', 'MediaListe'),
(251, 'CV.t2.Etage20.room60', 'Regarder la TV', 'MediaListe'),
(252, 'CV.t2.etage3.Room7', 'Regarder la TV', 'MediaListe'),
(253, 'CV.t2.etage3.Room8', 'Regarder la TV', 'MediaListe'),
(254, 'CV.t2.etage3.Room9', 'Regarder la TV', 'MediaListe'),
(255, 'CV.t2.etage4.Room10', 'Regarder la TV', 'MediaListe'),
(257, 'CV.t2.etage4.Room11', 'Regarder la TV', 'MediaListe'),
(258, 'CV.t2.etage4.Room12', 'Regarder la TV', 'MediaListe'),
(259, 'CV.t2.etage5.Room13', 'Regarder la TV', 'MediaListe'),
(261, 'CV.t2.etage5.Room14', 'Regarder la TV', 'MediaListe'),
(262, 'CV.t2.etage5.Room15', 'Regarder la TV', 'MediaListe'),
(263, 'CV.t2.etage6.room16', 'Regarder la TV', 'MediaListe'),
(264, 'CV.t2.etage6.Room17', 'Regarder la TV', 'MediaListe'),
(265, 'CV.t2.etage6.RoOm18', 'Regarder la TV', 'MediaListe'),
(266, 'CV.t2.etage7.Room19', 'Regarder la TV', 'MediaListe'),
(268, 'CV.t2.etage7.Room20', 'Regarder la TV', 'MediaListe'),
(269, 'CV.t2.etage7.Room21', 'Regarder la TV', 'MediaListe'),
(270, 'CV.t2.etage8.Room22', 'Regarder la TV', 'MediaListe'),
(271, 'CV.t2.etage8.Room23', 'Regarder la TV', 'MediaListe'),
(272, 'CV.t2.etage8.Room24', 'Regarder la TV', 'MediaListe'),
(273, 'CV.t2.etage9.Room25', 'Regarder la TV', 'MediaListe'),
(274, 'CV.t2.etage9.Room26', 'Regarder la TV', 'MediaListe'),
(275, 'CV.t2.etage9.Room27', 'Regarder la TV', 'MediaListe'),
(276, 'CV.police.Morgue', 'Frigo', 'CasiersListe'),
(279, 'Est.comm.arr', 'Armoire', 'CasiersListe'),
(280, 'Nord.auberge.culture', 'Armoire', 'CasiersListe'),
(281, 'Nord.auberge.c1', 'Penderie', 'CasiersListe'),
(282, 'Nord.auberge.c3', 'Penderie', 'CasiersListe'),
(283, 'Nord.auberge.c4', 'Placard', 'CasiersListe'),
(284, 'Nord.auberge.c9', 'Placard', 'CasiersListe'),
(285, 'Nord.auberge.c5', 'Placard', 'CasiersListe'),
(286, 'Nord.auberge.c6', 'Placard', 'CasiersListe'),
(287, 'Nord.auberge.c7', 'Placard', 'CasiersListe'),
(288, 'Nord.auberge.c8', 'Placard', 'CasiersListe'),
(289, 'Est.pavillons.hall.eta1.c1', 'Armoire', 'CasiersListe'),
(290, 'Est.pavillons.hall.eta1.c2', 'Armoire', 'CasiersListe'),
(291, 'Est.pavillons.hall.eta1.c3', 'Armoire', 'CasiersListe'),
(292, 'CV.t1.etage1.Room1', 'Meubles', 'CasiersListe'),
(293, 'Est.pavillons.hall.eta1.c4', 'Armoire', 'CasiersListe'),
(294, 'Est.pavillons.hall.eta1.c5', 'Armoire', 'CasiersListe'),
(295, 'CV.t1.etage1.room2', 'Meubles', 'CasiersListe'),
(296, 'Est.pavillons.hall.eta2.c1', 'Armoire', 'CasiersListe'),
(297, 'CV.t1.etage10.room19', 'Meubles', 'CasiersListe'),
(298, 'Est.pavillons.hall.eta2.c2', 'Armoire', 'CasiersListe'),
(299, 'CV.t1.etage10.room20', 'Meubles', 'CasiersListe'),
(300, 'Est.pavillons.hall.eta2.c3', 'Armoire', 'CasiersListe'),
(301, 'CV.t1.etage11.room21', 'Meubles', 'CasiersListe'),
(302, 'CV.t1.etage11.room22', 'Meubles', 'CasiersListe'),
(303, 'CV.t1.etage12.room23', 'Meubles', 'CasiersListe'),
(304, 'Est.pavillons.hall.eta2.c4', 'Armoire', 'CasiersListe'),
(305, 'CV.t1.etage12.room24', 'Meubles', 'CasiersListe'),
(306, 'Est.pavillons.hall.eta2.c5', 'Armoire', 'CasiersListe'),
(307, 'CV.t1.etage13.room25', 'Meubles', 'CasiersListe'),
(308, 'CV.t1.etage13.room26', 'Meubles', 'CasiersListe'),
(309, 'Est.pavillons.hall.eta3.c1', 'Armoire', 'CasiersListe'),
(310, 'CV.t1.etage14.room27', 'Meubles', 'CasiersListe'),
(311, 'Est.pavillons.hall.eta3.c2', 'Armoire', 'CasiersListe'),
(312, 'CV.t1.etage14.room28', 'Meubles', 'CasiersListe'),
(313, 'Est.pavillons.hall.eta3.c3', 'Armoire', 'CasiersListe'),
(314, 'CV.t1.etage15.room29', 'Meubles', 'CasiersListe'),
(315, 'Est.pavillons.hall.eta3.c4', 'Armoire', 'CasiersListe'),
(316, 'CV.t1.etage15.Room30', 'Meubles', 'CasiersListe'),
(317, 'Est.pavillons.hall.eta3.c5', 'Armoire', 'CasiersListe'),
(318, 'CV.t1.etage16.room31', 'Meubles', 'CasiersListe'),
(319, 'CV.t2.Etage1.room1', 'Meubles', 'CasiersListe'),
(321, 'CV.t2.Etage1.Room3', 'Meubles', 'CasiersListe'),
(322, 'CV.t2.etage10.Room28', 'Meubles', 'CasiersListe'),
(323, 'CV.t2.etage10.Room29', 'Meubles', 'CasiersListe'),
(324, 'CV.t2.etage10.Room30', 'Meubles', 'CasiersListe'),
(325, 'CV.t2.Etage11.Room31', 'Meubles', 'CasiersListe'),
(326, 'CV.t2.Etage11.Room32', 'Meubles', 'CasiersListe'),
(327, 'CV.t2.Etage11.Room33', 'Meubles', 'CasiersListe'),
(328, 'CV.t2.etage12.Room34', 'Meubles', 'CasiersListe'),
(329, 'CV.t2.etage12.Room35', 'Meubles', 'CasiersListe'),
(330, 'CV.t2.etage12.Room36', 'Meubles', 'CasiersListe'),
(331, 'CV.t2.etage13.Room37', 'Meubles', 'CasiersListe'),
(332, 'CV.t2.etage13.Room38', 'Meubles', 'CasiersListe'),
(333, 'CV.t2.etage13.Room39', 'Meubles', 'CasiersListe'),
(334, 'CV.t2.etage14.Room40', 'Meubles', 'CasiersListe'),
(335, 'CV.t2.etage14.Room41', 'Meubles', 'CasiersListe'),
(336, 'CV.t2.etage14.Room42', 'Meubles', 'CasiersListe'),
(337, 'CV.t2.etage15.Room43', 'Meubles', 'CasiersListe'),
(338, 'CV.t2.etage15.Room44', 'Meubles', 'CasiersListe'),
(339, 'CV.t2.etage15.Room45', 'Meuble', 'CasiersListe'),
(340, 'CV.t2.Etage18.Room52', 'Meubles', 'CasiersListe'),
(341, 'CV.t1.etage16.Room32', 'Meubles', 'CasiersListe'),
(342, 'CV.t1.etage17.room33', 'Meubles', 'CasiersListe'),
(343, 'CV.t1.etage17.room34', 'Meubles', 'CasiersListe'),
(344, 'CV.t2.Etage18.Room53', 'Meubles', 'CasiersListe'),
(345, 'CV.t1.etage18.room35', 'Meubles', 'CasiersListe'),
(346, 'CV.t2.Etage18.Room54', 'Meubles', 'CasiersListe'),
(347, 'CV.t1.etage18.room36', 'Meubles', 'CasiersListe'),
(348, 'CV.t2.etage19.Room55', 'Meubles', 'CasiersListe'),
(349, 'CV.t1.etage19.room38', 'Meubles', 'CasiersListe'),
(350, 'CV.t1.etage2.room3', 'Meubles', 'CasiersListe'),
(351, 'CV.t2.etage19.Room56', 'Meubles', 'CasiersListe'),
(352, 'CV.t2.etage19.room57', 'Meubles', 'CasiersListe'),
(353, 'CV.t1.etage2.Room4', 'Meubles', 'CasiersListe'),
(354, 'CV.t1.etage20.Room39', 'Meubles', 'CasiersListe'),
(355, 'CV.t2.etage2.Room4', 'Meubles', 'CasiersListe'),
(356, 'CV.t1.etage20.Room40', 'Meubles', 'CasiersListe'),
(357, 'CV.t2.etage2.Room5', 'Meubles', 'CasiersListe'),
(358, 'CV.t1.etage21.Room41', 'Meubles', 'CasiersListe'),
(359, 'CV.t1.etage21.Room42', 'Meubles', 'CasiersListe'),
(360, 'CV.t2.etage2.Room6', 'Meubles', 'CasiersListe'),
(361, 'CV.t1.etage3.room5', 'Meubles', 'CasiersListe'),
(362, 'CV.t1.etage3.Room6', 'Meubles', 'CasiersListe'),
(363, 'CV.t1.etage4.room7', 'Meubles', 'CasiersListe'),
(364, 'CV.t2.etage16.Room46', 'Meubles', 'CasiersListe'),
(365, 'CV.t2.etage16.Room47', 'Meubles', 'CasiersListe'),
(366, 'CV.t1.etage4.Room8', 'Meubles', 'CasiersListe'),
(367, 'CV.t1.etage5.room10', 'Meubles', 'CasiersListe'),
(368, 'CV.t2.etage16.Room48', 'Meubles', 'CasiersListe'),
(369, 'CV.t2.etage17.Room49', 'Meubles', 'CasiersListe'),
(370, 'CV.t1.etage5.room9', 'Meubles', 'CasiersListe'),
(371, 'CV.t2.etage17.Room50', 'Meubles', 'CasiersListe'),
(372, 'CV.t1.etage9.room18', 'Meubles', 'CasiersListe'),
(373, 'CV.t1.etage6.room11', 'Meubles', 'CasiersListe'),
(374, 'CV.t2.etage17.room51', 'Meubles', 'CasiersListe'),
(375, 'CV.t1.etage6.room12', 'Meubles', 'CasiersListe'),
(376, 'CV.t1.etage7.room13', 'Meubles', 'CasiersListe'),
(377, 'CV.t1.etage7.room14', 'Meubles', 'CasiersListe'),
(378, 'CV.t1.etage8.Room15', 'Meubles', 'CasiersListe'),
(379, 'CV.t1.etage8.room16', 'Meubles', 'CasiersListe'),
(380, 'CV.t1.etage9.room17', 'Meubles', 'CasiersListe'),
(381, 'CV.t2.Etage20.room58', 'Meubles', 'CasiersListe'),
(382, 'CV.t2.Etage20.Room59', 'Meubles', 'CasiersListe'),
(383, 'CV.t2.Etage20.room60', 'Meubles', 'CasiersListe'),
(384, 'CV.t2.etage3.Room7', 'Meubles', 'CasiersListe'),
(385, 'CV.t2.etage3.Room8', 'Meubles', 'CasiersListe'),
(386, 'CV.t2.etage3.Room9', 'Meubles', 'CasiersListe'),
(387, 'CV.t1.etage19.room37', 'Meubles', 'CasiersListe'),
(388, 'CV.t2.etage4.Room10', 'Meubles', 'CasiersListe'),
(389, 'CV.t2.etage4.Room11', 'Meubles', 'CasiersListe'),
(390, 'CV.t2.etage4.Room12', 'Meubles', 'CasiersListe'),
(391, 'CV.t2.etage5.Room13', 'Meubles', 'CasiersListe'),
(392, 'CV.t2.etage5.Room14', 'Meubles', 'CasiersListe'),
(393, 'CV.t2.etage5.Room15', 'Meubles', 'CasiersListe'),
(394, 'CV.t2.etage6.room16', 'Meubles', 'CasiersListe'),
(395, 'CV.t2.etage6.Room17', 'Placard', 'CasiersListe'),
(396, 'CV.t2.etage6.RoOm18', 'Meubles', 'CasiersListe'),
(399, 'CV.t2.etage7.Room19', 'Meubles', 'CasiersListe'),
(400, 'CV.t2.etage8.Room22', 'Meubles', 'CasiersListe'),
(401, 'CV.t2.etage8.Room23', 'Meubles', 'CasiersListe'),
(403, 'CV.t2.etage8.Room24', 'Armoire', 'CasiersListe'),
(404, 'CV.t2.etage9.Room25', 'Meubles', 'CasiersListe'),
(405, 'CV.t2.etage9.Room26', 'Armoire', 'CasiersListe'),
(406, 'CV.t2.etage9.Room27', 'Meubles', 'CasiersListe'),
(407, 'CV.t2.etage7.Room20', 'Meubles', 'CasiersListe'),
(408, 'CV.t2.etage7.Room21', 'Meubles', 'CasiersListe'),
(409, 'Ouest.univ.med', 'Laboratoire', 'LaboDrogue'),
(410, 'Ouest.univ.med', 'Frigo', 'CasiersListe'),
(411, 'Est.comm.imp.bureau', 'Ordinateur Fixe', 'OrdinateurFixe'),
(412, 'Nord.casino.bur', 'Meubles', 'CasiersListe'),
(414, 'Sud.boxe', 'S\'entrainer', 'Etudier'),
(415, 'Sud.clerks', 'Liste de commandes', 'Biblio'),
(416, 'JS', 'LOL', 'ReparerArme'),
(417, 'JS', 'Je ', 'ReparerDefense'),
(418, 'JS', 'suis', 'Recycler'),
(419, 'JS', 'un', 'TelephonerCabine'),
(420, 'JS', 'gros', 'Boutique'),
(421, 'JS', 'noob', 'Soigner'),
(428, 'Sud.recup', 'Recycler', 'Recycler'),
(429, 'CV.towerTV', 'Regarder la TV', 'MediaListe'),
(430, 'Est.puces.magasinArabe', 'Underground Market', 'Boutique'),
(431, 'CV.police.Vest', 'Casiers du personnel', 'CasiersListe'),
(434, 'Est.Electro', 'Examiner les télévisions', 'MediaListe'),
(435, 'Est.puces.magasinBlack', 'Derrière la Grille', 'Boutique'),
(436, 'CV.police', 'Bureau Accueil', 'CasiersListe'),
(440, 'Est.sushi.bur', 'G33ker sur le PC.', 'OrdinateurFixe'),
(441, 'Est.sushi.bur', 'Bureau et coffre', 'CasiersListe'),
(444, 'CV.mairie', 'Pile de formulaires', 'Biblio'),
(445, 'Nord', 'Affiches', 'Biblio'),
(449, 'Est.comm', 'Affiches', 'Biblio'),
(450, 'CV.t2.Etage20.gangcas', 'Labo de Drogues', 'LaboDrogue'),
(455, 'Est.comm.imp.bureau', 'Casier', 'CasiersListe'),
(459, 'CV.hopital.Hall.réa', 'Ré-animation', 'Soigner'),
(460, 'CV.police.asc.Sts', 'Casier', 'CasiersListe'),
(461, 'Est.comm.serru', 'Casier', 'CasiersListe'),
(462, 'CV.police.asc.training', 'Entraînements ', 'Etudier'),
(463, 'CV.agence.assist', 'Ordinateur', 'OrdinateurFixe'),
(464, 'CV.agence.assist', 'Téléphone ', 'TelephonerCabine'),
(465, 'CV.agence', 'Regarder la TV', 'MediaListe'),
(466, 'Sud.recup.ate', 'Réparation de défenses ', 'ReparerDefense'),
(467, 'Sud.recup.ate', 'Réparation d\'armes banches', 'ReparerArme'),
(468, 'Sud.clerks.arrsalle', 'Casiers', 'CasiersListe'),
(469, 'CV.police.Morgue', 'Casier', 'CasiersListe'),
(470, 'Est.Electro', 'Affiches', 'Biblio'),
(471, 'CV.hopital.SS.labo', 'Frigo', 'CasiersListe'),
(472, 'cv.hopital.e1.soins', 'Effectuer les soins', 'Soigner'),
(473, 'Sud.clerks', 'Regarder la télé', 'MediaListe'),
(474, 'Nord.ruelle.Scrap', 'Regarder la télé pourrie', 'MediaListe'),
(475, 'CV.police.Morgue.congel', 'Frigo', 'CasiersListe'),
(476, 'CV.t1.etage5.room5', 'Regarder la TV', 'MediaListe'),
(477, 'CV.t1.etage5.room5', 'Meubles', 'CasiersListe'),
(481, 'Nord.ruelle.Scrap', 'Vieux frigo', 'CasiersListe'),
(482, 'Sud.squat', 'Bar', 'Boutique'),
(483, 'Sud.squat.vest', 'Casiers', 'CasiersListe'),
(484, 'Nord.auberge.c2med', 'Rumeurs', 'Biblio'),
(486, 'CV.hopital.e1.medec', 'Casiers', 'CasiersListe'),
(487, 'CV.police.asc.Stocks', 'Stocks', 'CasiersListe'),
(490, 'Est.Electro', 'Cabine téléphonique', 'TelephonerCabine'),
(491, 'CV.tacos', 'A la carte.', 'Boutique'),
(492, 'Est.comm.tacos', 'A la carte.', 'Boutique'),
(493, 'Est.comm.tacos.frigo', 'Réserve', 'CasiersListe'),
(494, 'Sud.boxe.infi', 'Soigner les bobos...', 'Soigner'),
(495, 'Sud.boxe.infi', 'Pharmacie', 'CasiersListe'),
(496, 'CV.towerTV.infor', 'Armoire', 'CasiersListe'),
(497, 'CV.towerTV.infor', 'Ordinateur 1', 'OrdinateurFixe'),
(498, 'CV.towerTV.infor', 'Ordinateur 2', 'OrdinateurFixe'),
(499, 'CV.towerTV.infor', 'Atelier', 'Etudier'),
(501, 'CDP.soins', 'Infirmerie', 'Soigner'),
(502, 'CDP.soins', 'Réparation', 'ReparerArme'),
(503, 'CDP.soins', 'Rafistolage', 'ReparerDefense'),
(504, 'CDP.cou3', 'Casiers', 'CasiersListe'),
(505, 'CDP.cou3', 'Entrainement', 'Etudier'),
(506, 'Nord.casino', 'Regarder la TV', 'MediaListe'),
(509, 'Nord.ruelle.Scrap.Bureau', 'Entretien d\'armes à feu', 'ReparerArme'),
(510, 'Est.comm.serru.atel', 'Meubles', 'CasiersListe'),
(511, 'CV.police.asc.Stocks', 'Atelier d\'Erwan', 'ReparerArme'),
(512, 'Est.Electro', 'Ordinateur', 'OrdinateurFixe'),
(513, 'Sud.eau', 'Cache mal dissimulée', 'CasiersListe'),
(514, 'CDP.arene', 'Casiers partie privée', 'CasiersListe'),
(516, 'Est.comm.serru', 'Comptoir', 'Boutique'),
(517, 'Est.comm.wood', 'Boutique', 'Boutique'),
(518, 'Est.comm.wood', 'Emaüss', 'Recycler'),
(528, 'Nord.ruelle.Scrap.rotat', 'Table d\'opération / Soins', 'Soigner'),
(529, 'Nord.ruelle.Scrap.rotat', 'Laboratoire', 'LaboDrogue'),
(530, 'Nord.ruelle.Scrap.Bureau', 'S’entraîner sur l\'établi', 'Etudier'),
(531, 'Nord.ruelle.Scrap.rotat', 'Etudier les bouquins ', 'Etudier'),
(532, 'Nord.redv', 'Barre de pôle dance', 'Etudier'),
(533, 'Nord.ruelle.Scrap.Bureau', 'Casiers en bois', 'CasiersListe'),
(534, 'Nord.ruelle.Scrap.Bureau', 'Télévisions ', 'MediaListe'),
(535, 'CV.police.asc.Stocks', 'Stock mis en vente', 'Boutique'),
(536, 'Sud.recup.forge', 'Acheter', 'Boutique'),
(537, 'Sud.recup.forge.atelier', 'Réparer protections', 'ReparerDefense'),
(538, 'Sud.recup.forge.atelier', 'Réparer armes', 'ReparerArme'),
(539, 'Sud.recup.forge.atelier', 'Casier', 'CasiersListe'),
(540, 'Sud.boxe', 'Regarder la TV', 'MediaListe'),
(541, 'Ouest.auberge', 'Banque', 'Banque'),
(542, 'Ouest.auberge', 'Réparation', 'ReparerArme'),
(543, 'Ouest.auberge', 'Etudier', 'Etudier'),
(544, 'Ouest.auberge', 'Armure', 'ReparerDefense'),
(546, 'Ouest.univ', 'Laboratoire', 'LaboDrogue'),
(547, 'CV.hopital.Hall.salon.cafet', 'Casiers métallique', 'CasiersListe'),
(548, 'CV.hopital.Hall.salon.cafet', 'Comptoir', 'Boutique'),
(549, 'Sud.baranoob', 'Conversations', 'Biblio'),
(550, 'CV.Bâtiment abandonné', 'Compétences', 'Etudier'),
(551, 'CV.centralp', '', 'Etudier'),
(552, 'CV.centralp.enfant', 'Compétences', 'Etudier'),
(553, 'CV.centralp.ile', '', 'Etudier'),
(554, 'CV.hopital.Hall.salon.entrainement', 'Compétences', 'Etudier'),
(555, 'Ext.sas.camp', 'Compétences', 'Etudier'),
(556, 'Ext.sas.camp.baraquements', 'Compétences', 'Etudier'),
(557, 'Ext.sas.puces', 'Compétences', 'Etudier'),
(559, 'Nord.auberge.bureau.bloc', 'Compétences', 'Etudier'),
(560, 'Nord.Repère en ruines', 'Compétences', 'Etudier'),
(561, 'Ouest.Bâtiment abandonné', 'Compétences', 'Etudier'),
(562, 'Ouest.Manoir.Bureau', 'Compétences', 'Etudier'),
(563, 'Ouest.Manoir.Escalier.Labo', 'Compétences', 'Etudier'),
(565, 'Ouest.Squat', 'Compétences', 'Etudier'),
(566, 'Sud.baranoob', 'Compétences', 'Etudier'),
(567, 'Sud.recup', 'Compétences', 'Etudier'),
(568, 'Nord.CDC', 'Achats à l\'unité', 'Boutique'),
(569, 'Ext.sas.camp.baraquements', 'Se servir dans le stock', 'Boutique'),
(570, 'Ext.sas.camp.baraquements', 'Casiers', 'CasiersListe'),
(572, 'Sud.baranoob', 'Recharger Telephone', 'Banque'),
(573, 'Sud.baranoob', 'Passer le Visa Vert', 'Mairie'),
(574, 'Sud.baranoob', 'Boire un verre', 'Boutique'),
(576, 'Nord.auberge', 'Boutique', 'Boutique'),
(577, 'CV.brasserie', 'Boissons', 'Boutique'),
(579, 'Nord.auberge.bureau.bloc', 'Soins', 'Soigner'),
(581, 'Nord.auberge', 'Compétences', 'Etudier'),
(583, 'Ouest.Manoir.Escalier.Labo', 'Armoire', 'CasiersListe'),
(584, 'Ouest.Manoir.Escalier.Stock', 'Armoire', 'CasiersListe'),
(585, 'Ouest.Manoir.Bureau', 'Tiroir du bureau', 'CasiersListe'),
(586, 'Ouest.Manoir.Grind.Salon', 'Table de chevet', 'CasiersListe'),
(587, 'Nord.auberge.bureau', 'Casiers Métalliques', 'CasiersListe'),
(588, 'Nord.auberge', 'Malle Métallique', 'CasiersListe'),
(590, 'CachetteEldrim', 'Etude', 'Etudier'),
(591, 'Ouest.Manoir.Escalier.Stock', 'Coffre', 'Boutique'),
(592, 'CachetteEldrim', 'Cachette', 'CasiersListe'),
(593, 'Ouest.Manoir.Escalier.Etage.Grande Salle', 'S\'entrainer', 'Etudier'),
(594, 'Ouest.Manoir.Escalier.Etage.Chambre2', 'Meubles', 'CasiersListe'),
(595, 'Ext.sas', '', 'Boutique'),
(596, 'CachetteEldrim', 'Table de travail', 'ReparerArme'),
(597, 'Est.pavillons.couloir.chambre1', 'Table de nuit', 'CasiersListe'),
(598, 'Ouest.Manoir.Bureau.Souterrain', 'cavite rocheuse', 'CasiersListe'),
(599, 'ext.sas.camp.ext.Entrepot ', 'Ordinateur', 'OrdinateurFixe'),
(600, 'Nord.auberge.bureau', 'Infirmerie', 'Soigner'),
(601, 'CV.local.réserve', 'Armurerie', 'Etudier'),
(602, 'Test Eclipse', 'Banque', 'Banque'),
(603, 'Test Eclipse', 'soigner', 'Soigner'),
(604, 'Test Eclipse', 'biblio', 'Biblio'),
(605, 'Test Eclipse', 'casino', 'Casino'),
(606, 'Test Eclipse', 'distributeur', 'Distributeur'),
(607, 'Test Eclipse', 'etudier', 'Etudier'),
(608, 'Test Eclipse', 'guichet', 'Guichet'),
(609, 'Test Eclipse', 'labodrogue', 'LaboDrogue'),
(610, 'Test Eclipse', 'mairie', 'Mairie'),
(611, 'Test Eclipse', 'medialiste', 'MediaListe'),
(612, 'Test Eclipse', 'ordinateur fixe', 'OrdinateurFixe'),
(613, 'Test Eclipse', '123456789012345678901234567890', 'Producteur'),
(614, 'Test Eclipse', 'recycler', 'Recycler'),
(617, 'Test Eclipse', 'telephoner cabine', 'TelephonerCabine'),
(618, 'Test Eclipse', 'casierliste', 'CasiersListe'),
(619, 'Ouest.Manoir.Absolute.Ginger', 'Comptoir', 'Boutique'),
(620, 'Ouest.Manoir.Absolute.Ginger.Salon', 'Table de chevet', 'CasiersListe'),
(621, 'CachetteEldrim', 'Production', 'Producteur'),
(623, 'Ext.sas.camp', 'Tri du métal', 'Producteur'),
(624, 'Ouest.Manoir.Escalier.Labo', 'Préparation des réactifs', 'Producteur'),
(625, 'Nord.auberge.bureau.bloc', 'Vérification des composants', 'Producteur'),
(626, 'Nord.auberge.bureau', 'Préparation de bandage', 'Producteur'),
(627, 'CV.hopital.Hall.salon.reunion', 'Reprise du cuir', 'Producteur'),
(631, 'Ouest.eglise.cim', 'Jardinage', 'Producteur'),
(632, 'Test Eclipse', 'boutique', 'Boutique'),
(634, 'CachetteEldrim', 'Recharger téléphone', 'Banque'),
(635, 'Nord.auberge.bureau.prod1', 'Stérilisation de matériel', 'Producteur'),
(636, 'Nord.auberge.bureau.prod2', 'Préparer du matériel', 'Producteur'),
(637, 'Nord.auberge.bureau.bloc.prod1', 'Remise en état de prothèse', 'Producteur'),
(638, 'Nord.auberge.bureau.bloc.prod2', 'Remise en état de cybernétique', 'Producteur'),
(639, 'Ouest.Manoir.Escalier.Labo.prod1', 'Préparation des réactifs', 'Producteur'),
(640, 'Ouest.Manoir.Escalier.Labo.prod2', 'Synthèse et purification', 'Producteur'),
(641, 'CV.hopital.Hall.salon.reunion.prod1', 'Remise en état de protection', 'Producteur'),
(642, 'CV.hopital.Hall.salon.reunion.prod2', 'Armurerie High Tech', 'Producteur'),
(643, 'Ext.sas.camp.prod1', 'Affûtage et entretien simple', 'Producteur'),
(644, 'Ext.sas.camp.prod2', 'Forge', 'Producteur'),
(645, 'Ouest.eglise.cim.prod1', 'Plantation', 'Producteur'),
(646, 'ouest.eglise.cim.prod2', 'Récolter', 'Producteur'),
(647, 'ouest.eglise', 'Service', 'Boutique'),
(648, 'CachetteEldrim', 'Jardinage', 'Producteur'),
(649, 'Nord.auberge.bureau.bloc', 'Réparation et entretien', 'Producteur'),
(650, 'Nord.auberge.bureau.bloc', 'Conception de prothèse', 'Producteur'),
(651, 'Ouest.Manoir.Escalier.Labo', 'Travaux de laboratoire', 'Producteur'),
(652, 'Ouest.Manoir.Escalier.Labo', 'Synthèse et purifications', 'Producteur'),
(653, 'Ext.sas.camp', 'Affûtage et entretien', 'Producteur'),
(654, 'Ext.sas.camp', 'Forge d\'arme blanche', 'Producteur'),
(655, 'CV.hopital.Hall.salon.reunion', 'Entretien des armures', 'Producteur'),
(656, 'CV.hopital.Hall.salon.reunion', 'Tissage High-Tech', 'Producteur'),
(657, 'CV.hopital.Hall.salon.reunion', 'Compètence', 'Etudier'),
(658, 'Nord.auberge.bureau', 'Aseptiser le matériel', 'Producteur'),
(659, 'Nord.auberge.bureau', 'Maintenance des appareils', 'Producteur'),
(660, 'Ouest.eglise.cim', 'Plantation', 'Producteur'),
(661, 'Ouest.eglise.cim', 'Récolte', 'Producteur'),
(662, 'Noob.Zone 3', 'Casier métallique', 'CasiersListe'),
(663, 'Transit.rumeur', 'Nouveau Monde', 'MediaListe'),
(664, 'Transit.rumeur', 'Marché au puce', 'MediaListe'),
(665, 'Transit.rumeur', 'Arcadia', 'MediaListe'),
(666, 'Transit.rumeur', 'Eglise', 'MediaListe'),
(667, 'Transit.rumeur', 'Manoir', 'MediaListe'),
(668, 'Transit.rumeur', 'Centre ville', 'MediaListe'),
(669, 'Transit.rumeur', 'Squat clodo', 'MediaListe'),
(670, 'Sud.squat.clodo', 'Ragôt et racontard de clodo !', 'MediaListe'),
(673, 'CV.squat.clodo', 'Receleur', 'Recycler'),
(674, 'CV.squat.clodo', 'Vente de piquette !', 'Boutique'),
(675, 'CV.squat.clodo', 'Jeux de clodo !', 'Etudier'),
(676, 'CachetteEldrim', 'Bloc Opératoire', 'Soigner'),
(677, 'CachetteEldrim', 'Atelier d\'arme', 'ReparerArme'),
(678, 'CachetteEldrim', 'Atelier d\'armure', 'ReparerDefense'),
(679, 'CachetteEldrim', 'Soins', 'Soigner'),
(680, 'Test Eclipse', 'Reparer arme', 'ReparerArme'),
(681, 'Test Eclipse', 'Reparer défense', 'ReparerDefense'),
(682, 'Nord.auberge.bureau.bloc', 'Caisses K&G', 'CasiersListe'),
(683, 'Sud.usine.ruine.bureau', 'Rangement', 'CasiersListe'),
(686, 'egout.citém.plateforme', '', 'Producteur'),
(687, 'egout.ancienne.cité.banque', '', 'CasiersListe'),
(688, 'ext.entrepot.scène', 'En Scène ! ', 'Etudier'),
(689, 'Test. leuk Mael', 'test', 'Boutique'),
(690, 'CachetteEldrim', 'Vendeur', 'Boutique'),
(692, 'est.souterrain1.snow.gritche', 'Rangement', 'CasiersListe'),
(694, 'Ext.sas.camp', 'Malles', 'CasiersListe'),
(697, 'CV.brasserie.sal', 'casier mural', 'CasiersListe'),
(700, 'Ouest.Manoir.Escalier.Labo', 'Serre', 'Producteur'),
(703, 'Nord.auberge.cave', 'Réseau', 'OrdinateurFixe');
